### ISSUE TITLE
Suggestion: metadata modifiers

### ISSUE THREAD

**Issue by bkreider** [anaconda-distribution/anaconda-linter#125]
I suggest moving all of the linter directives under a top-level directive to avoid collisions with other people's usage of the extra section. 

For example:
```
extras:
  - anaconda-linter:
      skip-lints:
        - ...
      only-lint:
        - ...
```

This would carve out a namespace, since "extras" is an unmanaged free for all that prevents future collisions with how other community members might do linting.
